[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/auth/login"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/auth/callback"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
